### ISSUE TITLE
HOW THE FU- Hi, how do i use the BG change event ?

### ISSUE THREAD

**Issue by ODHG1** [DEV-idiotXD/Psychscripts-#2]
Help, i am dead, he in inside my body a ah. nah seriously how do i use the Bg change event ?

**Comment by DEV-idiotXD** [comment]
> Help, i am dead, he in inside my body a ah. nah seriously how do i use the Bg change event ?

idk how it works anymore ill try making a new one with instructions when im not sleepy just woke up
